# Generated by Django 3.0.5 on 2020-04-09 09:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcemessage',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resourcemessage',
            name='create_user',
            field=models.CharField(default='admin', max_length=100, verbose_name='创建人'),
        ),
    ]
