# Generated by Django 3.0.4 on 2020-04-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0002_auto_20200409_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcemessage',
            name='resource_code',
            field=models.IntegerField(default=999999, unique=True, verbose_name='资源编码'),
        ),
    ]
