# Generated by Django 3.0.4 on 2020-04-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0003_resourcemessage_resource_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcemessage',
            name='resource_code',
            field=models.IntegerField(default=10000, unique=True, verbose_name='资源编码'),
        ),
    ]
